name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        # Add your test command here, e.g., pytest
        echo "Running tests..."

    - name: Deploy
      if: github.ref == 'refs/heads/main' && success()
      run: |
        source venv/bin/activate
        # Add your deployment command here
        echo "Deploying application..."
